config/routes.rb
AsqUs::Application.routes.draw do
  
  root :to => 'home#index'

  match 'reps/dashboard' => 'reps#dashboard', :as => :rep_dashboard
  match 'reps/find_by_latlong' => 'reps#find_by_latlong'

  match 'users/home' => 'users#home', :as => :user_home
  match 'reps/home' => 'reps#home', :as => :rep_home
  match 'users/:id/reps' => 'users#get_reps', :as => :reps_for_user

  match 'map' => 'home#map'
  match 'faq' => 'home#faq'
  match 'demo' => 'home#demo'

  match 'polls/for_user' => 'polls#for_user', :as => :polls_for_user
  match 'polls/:id/vote/:option' => 'polls#vote', :as => :poll_vote
  match 'polls/:id/votes_per_day' => 'polls#votes_per_day', :as => :poll_votes_per_day
  match 'polls/:id/totals' => 'polls#totals', :as => :poll_totals

  match 'states/by_abbreviation' => 'states#by_abbreviation'

  post 'users/email_signup' => 'users#create'

  devise_for :users
  resources :users
  resources :reps
  resources :votes
  resources :poll_option_sets
  resources :groups
  resources :polls
  resources :states

end

app/models/poll_option_set.rb
class PollOptionSet < ActiveRecord::Base

  has_many :polls

end

app/controllers/poll_option_sets_controller.rb
class PollOptionSetsController < ApplicationController
  # GET /poll_option_sets
  # GET /poll_option_sets.json
  def index
    @poll_option_sets = PollOptionSet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @poll_option_sets }
    end
  end

  # GET /poll_option_sets/1
  # GET /poll_option_sets/1.json
  def show
    @poll_option_set = PollOptionSet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @poll_option_set }
    end
  end

  # GET /poll_option_sets/new
  # GET /poll_option_sets/new.json
  def new
    @poll_option_set = PollOptionSet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @poll_option_set }
    end
  end

  # GET /poll_option_sets/1/edit
  def edit
    @poll_option_set = PollOptionSet.find(params[:id])
  end

  # POST /poll_option_sets
  # POST /poll_option_sets.json
  def create
    @poll_option_set = PollOptionSet.new(params[:poll_option_set])

    respond_to do |format|
      if @poll_option_set.save
        format.html { redirect_to @poll_option_set, :notice => 'Poll option set was successfully created.' }
        format.json { render :json => @poll_option_set, :status => :created, :location => @poll_option_set }
      else
        format.html { render :action => "new" }
        format.json { render :json => @poll_option_set.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /poll_option_sets/1
  # PUT /poll_option_sets/1.json
  def update
    @poll_option_set = PollOptionSet.find(params[:id])

    respond_to do |format|
      if @poll_option_set.update_attributes(params[:poll_option_set])
        format.html { redirect_to @poll_option_set, :notice => 'Poll option set was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @poll_option_set.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /poll_option_sets/1
  # DELETE /poll_option_sets/1.json
  def destroy
    @poll_option_set = PollOptionSet.find(params[:id])
    @poll_option_set.destroy

    respond_to do |format|
      format.html { redirect_to poll_option_sets_url }
      format.json { head :ok }
    end
  end
end

app/helpers/poll_option_sets_helper.rb
module PollOptionSetsHelper
end

app/views/poll_option_sets/_form.html.erb
<%= form_for(@poll_option_set) do |f| %>
  <% if @poll_option_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll_option_set.errors.count, "error") %> prohibited this poll_option_set from being saved:</h2>

      <ul>
      <% @poll_option_set.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :options %><br />
    <%= f.text_area :options %>
  </div>
  <div class="field">
    <%= f.label :poll_id %><br />
    <%= f.number_field :poll_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poll_option_sets/edit.html.erb
<h1>Editing poll_option_set</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll_option_set %> |
<%= link_to 'Back', poll_option_sets_path %>

app/views/poll_option_sets/index.html.erb
<h1>Listing poll_option_sets</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Options</th>
    <th>Poll</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @poll_option_sets.each do |poll_option_set| %>
  <tr>
    <td><%= poll_option_set.type %></td>
    <td><%= poll_option_set.options %></td>
    <td><%= poll_option_set.poll_id %></td>
    <td><%= poll_option_set.user_id %></td>
    <td><%= link_to 'Show', poll_option_set %></td>
    <td><%= link_to 'Edit', edit_poll_option_set_path(poll_option_set) %></td>
    <td><%= link_to 'Destroy', poll_option_set, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Poll option set', new_poll_option_set_path %>

app/views/poll_option_sets/new.html.erb
<h1>New poll_option_set</h1>

<%= render 'form' %>

<%= link_to 'Back', poll_option_sets_path %>

app/views/poll_option_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @poll_option_set.type %>
</p>

<p>
  <b>Options:</b>
  <%= @poll_option_set.options %>
</p>

<p>
  <b>Poll:</b>
  <%= @poll_option_set.poll_id %>
</p>

<p>
  <b>User:</b>
  <%= @poll_option_set.user_id %>
</p>


<%= link_to 'Edit', edit_poll_option_set_path(@poll_option_set) %> |
<%= link_to 'Back', poll_option_sets_path %>