config/routes.rb
AsqUs::Application.routes.draw do
  
  root :to => 'home#index'

  match 'reps/dashboard' => 'reps#dashboard', :as => :rep_dashboard
  match 'reps/find_by_latlong' => 'reps#find_by_latlong'

  match 'users/home' => 'users#home', :as => :user_home
  match 'reps/home' => 'reps#home', :as => :rep_home
  match 'users/:id/reps' => 'users#get_reps', :as => :reps_for_user

  match 'map' => 'home#map'
  match 'faq' => 'home#faq'
  match 'demo' => 'home#demo'

  match 'polls/for_user' => 'polls#for_user', :as => :polls_for_user
  match 'polls/:id/vote/:option' => 'polls#vote', :as => :poll_vote
  match 'polls/:id/votes_per_day' => 'polls#votes_per_day', :as => :poll_votes_per_day
  match 'polls/:id/totals' => 'polls#totals', :as => :poll_totals

  match 'states/by_abbreviation' => 'states#by_abbreviation'

  post 'users/email_signup' => 'users#create'

  devise_for :users
  resources :users
  resources :reps
  resources :votes
  resources :poll_option_sets
  resources :groups
  resources :polls
  resources :states

end

app/models/rep.rb
class Rep < ActiveRecord::Base
  belongs_to :user
  belongs_to :state
  has_many :polls_created, :through => :user
  
  def self.find_by_latlong(lat, long)
    logger.info 'Looking up rep for ' + lat.to_s + ' ' + long.to_s

    state = self.find_state_reps_by_latlong(lat, long)
    federal = self.find_federal_reps_by_latlong(lat, long)
    state.merge(federal)
  end
  
  def self.find_state_reps_by_latlong(lat, long)
    GovKit::OpenStates
    results = GovKit::OpenStatesResource.get_uri('/legislators/geo?', :query => {:lat => lat, :long => long})
    representatives = Hash.new
    results.each{ |rep|
      representatives[rep.chamber + ' ' + rep.district] = rep.full_name
    }
    representatives
  end
  
  
  def self.find_federal_reps_by_latlong(lat, long)
    federal = Sunlight::Legislator.all_for(:latitude => lat, :longitude => long)
    representatives = Hash.new
    federal.each{ |rep|
      full_name = rep[1].firstname + ' ' + rep[1].lastname
      representatives[rep[1].govtrack_id] = full_name
    }
    representatives
  end
  
end

app/controllers/reps_controller.rb
class RepsController < ApplicationController

  before_filter :authenticate_user!, :only => [ :home ]
  #before_filter :assert_rep!, :only => [ :home ]

  def home
    @reps = Rep.all
    @rep = current_user.rep
    @polls = Poll.all

    if @rep.nil?
      return redirect_to :user_home, :error => 'Oops, you must be democratically elected to view that page.'
    end

    return redirect_to reps_url( :anchor => 'home' )
  end
  
  
  def find_by_latlong
    return render :json => Rep.find_by_latlong(params[:lat], params[:long])
  end


  # GET /reps
  # GET /reps.json
  def index
    #return redirect_to :controller => :rep, :action => :home
    @polls = Poll.all
    @reps = Rep.all
    
    respond_to do |format|
      format.html
      format.json { render :json => @reps, :include => :user }
    end
  end


  def list
    @reps = Rep.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @reps }
    end
  end


  # GET /reps/1
  # GET /reps/1.json
  def show
    @rep = Rep.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @rep }
    end
  end

  # GET /reps/new
  # GET /reps/new.json
  def new
    @rep = Rep.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @rep }
    end
  end

  # GET /reps/1/edit
  def edit
    @rep = Rep.find(params[:id])
  end

  # POST /reps
  # POST /reps.json
  def create
    @rep = Rep.new(params[:rep])

    respond_to do |format|
      if @rep.save
        format.html { redirect_to @rep, :notice => 'Rep was successfully created.' }
        format.json { render :json => @rep, :status => :created, :location => @rep }
      else
        format.html { render :action => "new" }
        format.json { render :json => @rep.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reps/1
  # PUT /reps/1.json
  def update
    @rep = Rep.find(params[:id])

    respond_to do |format|
      if @rep.update_attributes(params[:rep])
        format.html { redirect_to @rep, :notice => 'Rep was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @rep.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reps/1
  # DELETE /reps/1.json
  def destroy
    @rep = Rep.find(params[:id])
    @rep.destroy

    respond_to do |format|
      format.html { redirect_to reps_url }
      format.json { head :ok }
    end
  end
end

app/helpers/reps_helper.rb
module RepsHelper
end

app/views/reps/_form.html.erb
<%= form_for(@rep) do |f| %>
  <% if @rep.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rep.errors.count, "error") %> prohibited this rep from being saved:</h2>

      <ul>
      <% @rep.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reps/_nav.html.haml
.nav#nav.leftRounded
  %a#communityNav.navItem{ :href =>  '#community' } Community
  %a#homeNav.navItem{ :href =>  "#home" } Home
  %a#askNav.navItem{ :href =>  "#ask" } Ask
  %a#answerNav.navItem{ :href =>  "#answer" } Answer

app/views/reps/dashboard.html.haml
#notice
  = notice

%p
  %b User:
  = @rep.user_id


= link_to 'Edit', edit_rep_path(@rep) |
= link_to 'Back', reps_path

app/views/reps/edit.html.erb
<h1>Editing rep</h1>

<%= render 'form' %>

<%= link_to 'Show', @rep %> |
<%= link_to 'Back', reps_path %>

app/views/reps/home.html.haml
%p
  %b User:
  = @rep.user_id


= link_to 'Edit', edit_rep_path(@rep) |
= link_to 'Back', reps_path

app/views/reps/index.html.haml
:javascript
  $(function() {
    window.router = new AsqUs.Routers.RepsRouter({rep: #{@rep.to_json.html_safe}, polls: #{@polls.to_json.html_safe}});
    Backbone.history.start();
  //var nav = document.getElementById('nav');
  //window.setTimeout (function() {
    var nav = document.getElementById('nav');
    //nav.style.WebkitTransition = '-webkit-transform 300ms ease-in-out';
    //nav.style.WebkitTransition = '-webkit-tap-highlight-color: rgba(0,0,0,0)';
    //added to reps style sheet
    //nav.style.WebkitTransform = 'translate3d(0, 0, 0) rotate(0deg)';
    nav.style.WebkitTransition = 'backface-visibility:hidden';
    nav.style.WebkitTransition = '-webkit-backface-visibility:hidden'; /* Chrome and Safari */
    nav.style.WebkitTransition = '-moz-backface-visibility:hidden'; /* Firefox */
  //}, 0);
  });




#rep_wrapper
  = render :partial => 'reps/nav'
  #content.rightRounded

app/views/reps/new.html.erb
<h1>New rep</h1>

<%= render 'form' %>

<%= link_to 'Back', reps_path %>

app/views/reps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @rep.user_id %>
</p>


<%= link_to 'Edit', edit_rep_path(@rep) %> |
<%= link_to 'Back', reps_path %>