config/routes.rb
AsqUs::Application.routes.draw do
  
  root :to => 'home#index'

  match 'reps/dashboard' => 'reps#dashboard', :as => :rep_dashboard
  match 'reps/find_by_latlong' => 'reps#find_by_latlong'

  match 'users/home' => 'users#home', :as => :user_home
  match 'reps/home' => 'reps#home', :as => :rep_home
  match 'users/:id/reps' => 'users#get_reps', :as => :reps_for_user

  match 'map' => 'home#map'
  match 'faq' => 'home#faq'
  match 'demo' => 'home#demo'

  match 'polls/for_user' => 'polls#for_user', :as => :polls_for_user
  match 'polls/:id/vote/:option' => 'polls#vote', :as => :poll_vote
  match 'polls/:id/votes_per_day' => 'polls#votes_per_day', :as => :poll_votes_per_day
  match 'polls/:id/totals' => 'polls#totals', :as => :poll_totals

  match 'states/by_abbreviation' => 'states#by_abbreviation'

  post 'users/email_signup' => 'users#create'

  devise_for :users
  resources :users
  resources :reps
  resources :votes
  resources :poll_option_sets
  resources :groups
  resources :polls
  resources :states

end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, :notice => 'Group was successfully created.' }
        format.json { render :json => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.json { render :json => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, :notice => 'Group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :ok }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :members %><br />
    <%= f.number_field :members %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div id="groups"></div>

<script type="text/javascript">
  $(function() {
    window.router = new AsqUs.Routers.GroupsRouter({groups: <%=
        @groups.to_json.html_safe -%>});
    Backbone.history.start();
  });
</script>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @group.title %>
</p>

<p>
  <b>Members:</b>
  <%= @group.members %>
</p>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>