config/routes.rb
AsqUs::Application.routes.draw do
  
  root :to => 'home#index'

  match 'reps/dashboard' => 'reps#dashboard', :as => :rep_dashboard
  match 'reps/find_by_latlong' => 'reps#find_by_latlong'

  match 'users/home' => 'users#home', :as => :user_home
  match 'reps/home' => 'reps#home', :as => :rep_home
  match 'users/:id/reps' => 'users#get_reps', :as => :reps_for_user

  match 'map' => 'home#map'
  match 'faq' => 'home#faq'
  match 'demo' => 'home#demo'

  match 'polls/for_user' => 'polls#for_user', :as => :polls_for_user
  match 'polls/:id/vote/:option' => 'polls#vote', :as => :poll_vote
  match 'polls/:id/votes_per_day' => 'polls#votes_per_day', :as => :poll_votes_per_day
  match 'polls/:id/totals' => 'polls#totals', :as => :poll_totals

  match 'states/by_abbreviation' => 'states#by_abbreviation'

  post 'users/email_signup' => 'users#create'

  devise_for :users
  resources :users
  resources :reps
  resources :votes
  resources :poll_option_sets
  resources :groups
  resources :polls
  resources :states

end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :poll
  belongs_to :voter, :class_name => 'User'
  
  
  validates_presence_of :poll_option_set_index, :message => 'You must select an option for this poll'
  validates :voter_id,
    :uniqueness => {
      :scope => :poll_id,
      :allow_nil => true,
      :message => 'You have already voted for this poll'
    }


end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @votes }
    end
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
    @vote = Vote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @vote }
    end
  end

  # GET /votes/new
  # GET /votes/new.json
  def new
    @vote = Vote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @vote }
    end
  end

  # GET /votes/1/edit
  def edit
    @vote = Vote.find(params[:id])
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(params[:vote])

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, :notice => 'Vote was successfully created.' }
        format.json { render :json => @vote, :status => :created, :location => @vote }
      else
        format.html { render :action => "new" }
        format.json { render :json => @vote.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /votes/1
  # PUT /votes/1.json
  def update
    @vote = Vote.find(params[:id])

    respond_to do |format|
      if @vote.update_attributes(params[:vote])
        format.html { redirect_to @vote, :notice => 'Vote was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @vote.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy

    respond_to do |format|
      format.html { redirect_to votes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :poll_option_set_index %><br />
    <%= f.number_field :poll_option_set_index %>
  </div>
  <div class="field">
    <%= f.label :poll_id %><br />
    <%= f.number_field :poll_id %>
  </div>
  <div class="field">
    <%= f.label :voter_id %><br />
    <%= f.number_field :voter_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <tr>
    <th>Poll option set index</th>
    <th>Poll</th>
    <th>Voter</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @votes.each do |vote| %>
  <tr>
    <td><%= vote.poll_option_set_index %></td>
    <td><%= vote.poll_id %></td>
    <td><%= vote.voter_id %></td>
    <td><%= link_to 'Show', vote %></td>
    <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
    <td><%= link_to 'Destroy', vote, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Poll option set index:</b>
  <%= @vote.poll_option_set_index %>
</p>

<p>
  <b>Poll:</b>
  <%= @vote.poll_id %>
</p>

<p>
  <b>Voter:</b>
  <%= @vote.voter_id %>
</p>


<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>